### ISSUE TITLE
Error: could not determine executable to run

### ISSUE THREAD

**Issue by mijailr** [rkotze/git-mob-vs-code#47]
### Prerequisites

- [x] [Checked that your issue isn't already filed][git-mob-vs-code issues]
- [x] Tried upgrading to the latest git-mob-vs-code and git-mob version (`npm i -g git-mob`)
- [x] Tried upgrading to the latest git version (`brew upgrade git` if installed with Homebrew/Linuxbrew)

[git-mob-vs-code issues]: https://github.com/rkotze/git-mob-vs-code/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description

When using npm v7.0.5 seems like with the new version and the replacement of npx to run the git mob isn't working properly. 

```
0 verbose cli [
0 verbose cli   '/Users/user/.asdf/installs/nodejs/12.18.3/bin/node',
0 verbose cli   '/Users/user/.asdf/installs/nodejs/12.18.3/.npm/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'git',
0 verbose cli   'mob'
0 verbose cli ]
1 info using npm@7.0.5
2 info using node@v12.18.3
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/Users/user/.asdf/installs/nodejs/12.18.3/.npm/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Volumes/Workspace/project/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/user/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/Users/user/.asdf/installs/nodejs/12.18.3/.npm/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 6ms
19 verbose npm-session 701ad7404671dde4
20 timing npm:load Completed in 11ms
21 http fetch GET 200 https://registry.npmjs.org/git 10ms (from cache)
22 timing command:exec Completed in 22ms
23 verbose stack Error: could not determine executable to run
23 verbose stack     at getBinFromManifest (/Users/user/.asdf/installs/nodejs/12.18.3/.npm/lib/node_modules/npm/lib/exec.js:243:23)
23 verbose stack     at exec (/Users/user/.asdf/installs/nodejs/12.18.3/.npm/lib/node_modules/npm/lib/exec.js:129:15)
24 verbose cwd /Volumes/Workspace/project
25 verbose Darwin 19.6.0
26 verbose argv "/Users/user/.asdf/installs/nodejs/12.18.3/bin/node" "/Users/user/.asdf/installs/nodejs/12.18.3/.npm/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "git" "mob"
27 verbose node v12.18.3
28 verbose npm  v7.0.5
29 error could not determine executable to run
30 verbose exit 1
```

### Steps to Reproduce

1. Install npm 7
2. Use latest version of git-mob-vs-code
3. try to open gitmob on vscode

### Versions

- operating system and version: MacOS 10.15.7
- git-mob-vs-code version: 1.9.0
- git-mob version (`git-mob --version`): 1.1.0
- git version (`git --version`): 2.29.1

### Additional Information

Git mob as command line tool is working properly, it's just the vscode plugin failing.

**Comment by mijailr** [comment]
Oh, seems like it's solved if you use the latest version of npx

**Comment by rkotze** [comment]
@mijailr Thanks for reporting this issue. 

Was the version of `npx` not compatible with the version of `npm` you had installed?

**Comment by mijailr** [comment]
Yes, was the default version for node v12.18.3 but I recently installed the npm@7

**Comment by rkotze** [comment]
Closing as you resolved it.

**Comment by tobiasdiez** [comment]
I encounter the same error with `npx 7.6.3`. 
```
> npx git mob --list
npm ERR! could not determine executable to run
```
but using `git-mob` works:
```
> npx git-mob --list
hh Hulk Hogan hulk_hogan22@hotmail.org
```
